# Generated by Django 4.1 on 2022-08-25 17:26

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=accounts.models.upload_img)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/', validators=[accounts.models.validate_file_extension])),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, validators=[accounts.models.phone_validat])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
