# Generated by Django 4.1 on 2022-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'full time'), ('PT', 'part time')], max_length=15)),
                ('experience', models.IntegerField(default=1)),
                ('jop_describtion', models.TextField(max_length=1000)),
                ('puplish_date', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField(default=1)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
