# Generated by Django 4.1 on 2022-08-18 14:06

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name=job.models.upload_img),
            preserve_default=False,
        ),
    ]
