# Generated by Django 4.1 on 2022-08-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_name_location_city_location_countery'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.location'),
            preserve_default=False,
        ),
    ]
