# Generated by Django 4.1 on 2022-08-22 12:22

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_slug_alter_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='cv/', validators=[job.models.validate_file_extension])),
                ('coverletter', models.TextField(max_length=500)),
            ],
        ),
    ]
