# Generated by Django 4.1 on 2022-08-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='job',
            field=models.ManyToManyField(related_name='applay_job', to='job.job'),
        ),
    ]
