# Generated by Django 4.1 on 2022-08-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_applicants_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
