# Generated by Django 4.1 on 2022-08-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_applicants_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='job',
        ),
        migrations.AddField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applay_job', to='job.job'),
            preserve_default=False,
        ),
    ]
